### ISSUE TITLE
Data directory failing to mount in container (versioning branch)

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girderfs#15]
**Problem**:
While testing the versioning branch, the data directory fails to mount.

**Test steps**:
* Create a tale
* Add external data
* Start the tale
* Inspect data directory in container

**Expected results**:
External data is available in container

**Actual results**:
`ls ../data` results in `invalid argument`

Looking at the celery_worker logs, I first see the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/girderfs", line 11, in <module>
    load_entry_point('girderfs', 'console_scripts', 'girderfs')()
  File "/girderfs/girderfs/__main__.py", line 71, in main
  File "/girderfs/girderfs/core.py", line 536, in __init__
  File "/girderfs/girderfs/core.py", line 127, in __init__
  File "/girderfs/girderfs/core.py", line 549, in _load_object
  File "/girderfs/girderfs/core.py", line 558, in _populate_mount_points
  File "/girderfs/girderfs/core.py", line 568, in _add_session_entry
AttributeError: module 'logging' has no attribute 'isEnabledFor'
```

Apparently the `isEnabledFor` method is being used incorrectly. Removing these lines, I then see:
```
girderfs --hostns -c wt_dms --api-url http://10.0.27.5:8080/api/v1 --api-key XXX /var/lib/docker/volumes/5fb6b44ec2c381b57ab4eb86_willis8_VzjgJ6/_data/data 5fb6c4e10e81cbf2d44cd5f5

Traceback (most recent call last):
  File "/usr/local/bin/girderfs", line 11, in <module>
    load_entry_point('girderfs', 'console_scripts', 'girderfs')()
  File "/girderfs/girderfs/__main__.py", line 71, in main
  File "/girderfs/girderfs/core.py", line 535, in __init__
  File "/girderfs/girderfs/core.py", line 127, in __init__
  File "/girderfs/girderfs/core.py", line 548, in _load_object
  File "/girderfs/girderfs/core.py", line 557, in _populate_mount_points
  File "/girderfs/girderfs/core.py", line 572, in _add_session_entry
  File "/girderfs/girderfs/core.py", line 582, in _cache_mkdirs
  File "/girderfs/girderfs/core.py", line 88, in __getitem__
  File "/usr/local/lib/python3.8/dist-packages/diskcache/core.py", line 1236, in __getitem__
    raise KeyError(key)
KeyError: '5fb6c4e10e81cbf2d44cd5f5'
```

**Comment by craig-willis** [comment]
Fixed by https://github.com/whole-tale/girderfs/pull/18
